DROP PROCEDURE IF EXISTS DELETE_PORTAL_USER;
CREATE PROCEDURE DELETE_PORTAL_USER (
	IN P_USER_ID INT
  , OUT P_ERROR_NO INT
)
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET P_ERROR_NO=0;
	SET P_ERROR_NO = 1;

	START TRANSACTION;

  DELETE FROM SYS_USER WHERE USER_ID = P_USER_ID;
  DELETE FROM USER_DEP_RELA WHERE USER_ID = P_USER_ID;
  DELETE FROM USER_ROLE_RELA WHERE USER_ID = P_USER_ID;
  DELETE FROM USER_DASHBOARD WHERE USER_ID = P_USER_ID;
  DELETE FROM PAGE_CONFIG WHERE USER_ID = P_USER_ID;
  DELETE FROM PAGE_SEC_CONFIG WHERE USER_ID = P_USER_ID;

	IF P_ERROR_NO = 0 THEN
		ROLLBACK;
	ELSE
		COMMIT;
	END IF;

END;
