DROP PROCEDURE IF EXISTS INSERT_USER_ROLE;
DELIMITER //
CREATE PROCEDURE INSERT_USER_ROLE (
	IN P_ROLE_NAME VARCHAR(40)
	, IN P_ROLE_STATE	INT
	, IN P_ROLE_TYPE_ID	INT
	, IN P_MEMBER_COND	VARCHAR(21840)
  , OUT P_ERROR_NO INT
)
BEGIN

	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET P_ERROR_NO=0;
	SET P_ERROR_NO = 1;

	START TRANSACTION;

	INSERT INTO USER_ROLE (ROLE_NAME, ROLE_STATE, ROLE_TYPE_ID, CRE_TIME, UPD_TIME)
	VALUES (
    		  P_ROLE_NAME,
    		  P_ROLE_STATE,
    		  P_ROLE_TYPE_ID,
    		  NOW(),
					NOW()
	);

	SET @NEW_ROLE_ID = LAST_INSERT_ID();

	SET @SQLTEXT = CONCAT('INSERT INTO USER_ROLE_RELA (USER_ID, ROLE_ID, UPD_TIME, CRE_TIME) '
								'SELECT USER_ID, ?, NOW(), NOW() '
								'FROM '
								'	(SELECT DISTINCT U.USER_ID'
								'		FROM SYS_USER U'
								'		JOIN USER_ROLE_RELA UR ON U.USER_ID = UR.USER_ID'
								'		JOIN USER_ROLE R ON UR.ROLE_ID = R.ROLE_ID'
								'		WHERE ', P_MEMBER_COND, ') T');

	PREPARE STMT FROM @SQLTEXT;
	EXECUTE STMT USING @NEW_ROLE_ID;
	DEALLOCATE PREPARE STMT;


	IF P_ERROR_NO = 0 THEN
		ROLLBACK;
	ELSE
		COMMIT;
	END IF;

END//
