DROP PROCEDURE IF EXISTS PRODUCE_EXT_APP_LIST;
DELIMITER //
CREATE PROCEDURE PRODUCE_EXT_APP_LIST (
	IN P_ROLE_ID INT
)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE CNT INT DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

	CREATE TABLE IF NOT EXISTS `TMP_SYS_MENU` (
		`menu_id`       INT(11) NOT NULL COMMENT '菜单ID',
		`super_menu_id` INT(11) DEFAULT NULL COMMENT '上级菜单ID',
		`menu_cn_name`  VARCHAR(40) DEFAULT NULL COMMENT '菜单中文名',
		`menu_name`     VARCHAR(40) DEFAULT NULL COMMENT '菜单名称',
		`menu_icon_url` VARCHAR(200) DEFAULT NULL COMMENT '菜单图标URL',
		`menu_url`      VARCHAR(200) DEFAULT NULL COMMENT '菜单功能URL',
		`menu_level`    INT(11) NOT NULL COMMENT '菜单级别',
		`menu_state`    INT(11) NOT NULL COMMENT '菜单状态',
		`app_id`        INT(11) DEFAULT NULL COMMENT '对应的应用ID',
		`disp_order`    INT(11) DEFAULT NULL COMMENT '显示顺序',
		`cre_time`      TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
		`upd_time`      TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
		`show_on_init`  INT,
		`show_order`    INT,
		PRIMARY KEY (`MENU_ID`)
	) ENGINE=MEMORY DEFAULT CHARSET=UTF8;

	TRUNCATE TABLE TMP_SYS_MENU;

	IF P_ROLE_ID IS NULL THEN
		INSERT INTO TMP_SYS_MENU SELECT M.*, NULL AS SHOW_ON_INIT, NULL AS SHOW_ORDER
		FROM SYS_MENU M WHERE APP_ID IS NOT NULL AND MENU_STATE = 0;
	ELSE
		INSERT INTO TMP_SYS_MENU SELECT M.*, P.SHOW_ON_INIT, P.SHOW_ORDER
		FROM SYS_MENU M, MENU_PRIVILEGE P
		WHERE M.MENU_ID = P.MENU_ID
		AND P.ROLE_ID = P_ROLE_ID
		AND M.MENU_STATE = 0
		AND M.APP_ID IS NOT NULL;
	END IF;

	WHILE DONE = 0 DO
		INSERT INTO TMP_SYS_MENU
		SELECT M.*, NULL AS SHOW_ON_INIT, NULL AS SHOW_ORDER
		FROM (SELECT * FROM SYS_MENU WHERE MENU_ID NOT IN (SELECT MENU_ID FROM TMP_SYS_MENU)) M,
					(SELECT DISTINCT SUPER_MENU_ID FROM TMP_SYS_MENU) T
		WHERE M.MENU_ID = T.SUPER_MENU_ID;

		SELECT ROW_COUNT() INTO CNT;
		IF CNT = 0 THEN
			SET DONE = 1;
		END IF;

	END WHILE;

	SELECT * FROM TMP_SYS_MENU;

END//
