DROP PROCEDURE IF EXISTS PRODUCE_EXT_APP_LIST;
CREATE PROCEDURE PRODUCE_EXT_APP_LIST (
	IN P_ROLE_ID INT
)
BEGIN
	DECLARE DONE INT DEFAULT 0;
	DECLARE CNT INT DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;

	CREATE TEMPORARY TABLE IF NOT EXISTS `TMP_SYS_MENU` (
		`MENU_ID` INT(11) NOT NULL COMMENT '菜单ID',
		`SUPER_MENU_ID` INT(11) DEFAULT NULL COMMENT '上级菜单ID',
		`MENU_CN_NAME` VARCHAR(40) DEFAULT NULL COMMENT '菜单中文名',
		`MENU_NAME` VARCHAR(40) DEFAULT NULL COMMENT '菜单名称',
		`MENU_ICON_URL` VARCHAR(200) DEFAULT NULL COMMENT '菜单图标URL',
		`MENU_URL` VARCHAR(200) DEFAULT NULL COMMENT '菜单功能URL',
		`MENU_LEVEL` INT(11) NOT NULL COMMENT '菜单级别',
		`MENU_STATE` INT(11) NOT NULL COMMENT '菜单状态',
		`APP_ID` INT(11) DEFAULT NULL COMMENT '对应的应用ID',
		`DISP_ORDER` INT(11) DEFAULT NULL COMMENT '显示顺序',
		`CRE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
		`UPD_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
		`SHOW_ON_INIT` INT,
		`SHOW_ORDER` INT,
		PRIMARY KEY (`MENU_ID`)
	) ENGINE=MEMORY DEFAULT CHARSET=UTF8;

	TRUNCATE TABLE TMP_SYS_MENU;

	IF P_ROLE_ID IS NULL THEN
		INSERT INTO TMP_SYS_MENU SELECT M.*, NULL AS SHOW_ON_INIT, NULL AS SHOW_ORDER
		FROM SYS_MENU M WHERE APP_ID IS NOT NULL AND MENU_STATE = 0;
	ELSE
		INSERT INTO TMP_SYS_MENU SELECT M.*, P.SHOW_ON_INIT, P.SHOW_ORDER
		FROM SYS_MENU M, MENU_PRIVILEGE P
		WHERE M.MENU_ID = P.MENU_ID
		AND P.ROLE_ID = P_ROLE_ID
		AND M.MENU_STATE = 0
		AND M.APP_ID IS NOT NULL;
	END IF;

	WHILE DONE = 0 DO
		INSERT INTO TMP_SYS_MENU
		SELECT M.*, NULL AS SHOW_ON_INIT, NULL AS SHOW_ORDER
		FROM (SELECT * FROM SYS_MENU WHERE MENU_ID NOT IN (SELECT MENU_ID FROM TMP_SYS_MENU)) M,
					(SELECT DISTINCT SUPER_MENU_ID FROM TMP_SYS_MENU) T
		WHERE M.MENU_ID = T.SUPER_MENU_ID;

		SELECT ROW_COUNT() INTO CNT;
		IF CNT = 0 THEN
			SET DONE = 1;
		END IF;

	END WHILE;

	SELECT * FROM TMP_SYS_MENU;

END;
